homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 180
  unit_system: metric
  time_zone: Europe/Moscow
  
  
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

lovelace:
  mode: yaml

# Text to speech
tts:
  - platform: google_translate

group: !include includes/groups.yaml
automation: !include includes/automations.yaml
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml
yeelight: !include includes/yeelight.yaml


sensor: !include_dir_merge_list includes/sensors
