title: Home Assistant - сервер
views:

  - title: Главная
    id: main
    icon: mdi:home-assistant
    
    cards:

      - type: vertical-stack
        cards:
        
        - type: markdown
          content: >
             **Текущее состояние**
             
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.time
              name: Текущее время
              icon: mdi:clock-outline
            - entity: sensor.date
              name: Дата
              icon: mdi:calendar-check-outline
              
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.maria_db_size
              name: Объем БД
              icon: mdi:database
              
        - type: gauge
          name: Температура CPU
          unit: '°C'
          entity: sensor.cpu_temperature
          scan_interval: 30

      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Графики** 

        - type: horizontal-stack
          cards:

           - type: gauge
             name: Загрузка CPU
             unit: '%'
             entity: sensor.processor_use
             severity:
                green: 0
                yellow: 60
                red: 85
             
           - type: gauge
             name: Загрузка ОЗУ
             unit: '%'
             entity: sensor.memory_use_percent
             severity:
                green: 0
                yellow: 60
                red: 85
                
        - type: horizontal-stack
          cards:

           - type: gauge
             name: Диск заполнен
             unit: '%'
             entity: sensor.disk_use_percent
             severity:
                green: 0
                yellow: 60
                red: 85    
                
           - type: gauge
             name: Свободное место
             unit: 'Гб'
             min: 0
             max: 64
             entity: sensor.disk_free
             severity:
                red: 2
                yellow: 6
                green: 8
                
        - type: history-graph
          entities:
           - entity: sensor.maria_db_size
             name: Maria DB
                
              
  - title: Погода
    icon: mdi:weather-partly-snowy-rainy
    
    cards:

        - type: weather-forecast
          entity: weather.home_assistant 


  - title: Освещение
    icon: mdi:home-lightbulb
    
    cards:

        - type: entities
          show_header_toggle: false
          entities:
            - entity: light.yeelight_strip_2
          
        - type: light
          entity: light.yeelight_strip_2
          name: Лента
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          