device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.1-30
    home_interval: 10

sensor:
  - platform: rest
    resource_template: !secret time_to_work
    name: Time to work
    scan_interval: 180
    value_template: '{{ value_json.direct.time }}'
    unit_of_measurement: "мин"
    json_attributes:
      - jamsRate
      - jamsMeasure
      
  - platform: template
    sensors: 
      papas_location:
        value_template: >-          
          {% if is_state('person.dima', 'home') %}
            дома
          {% elif is_state('device_tracker.mi_mix_3', 'tushino') %}
            у бабушки
          {% elif is_state('device_tracker.mi_mix_3', 'altufevo') %}
            у родителей
          {% elif is_state('device_tracker.mi_mix_3', 'dimas_work') %}
            на работе
          {% elif is_state('device_tracker.mi_mix_3', 'shiha') %}
            у родителей мамы
          {% elif is_state('device_tracker.mi_mix_3', 'pokrov') %}
            на даче
          {% else %}
            где-то
          {% endif %}
        icon_template: >-
          {% if is_state('person.dima', 'home') %}
            mdi:home
          {% elif is_state('device_tracker.mi_mix_3', 'tushino') %}
            mdi:face-woman
          {% elif is_state('device_tracker.mi_mix_3', 'altufevo') %}
            mdi:human-male-female
          {% elif is_state('device_tracker.mi_mix_3', 'dimas_work') %}
            mdi:office-building-marker-outline
          {% elif is_state('device_tracker.mi_mix_3', 'shiha') %}
            mdi:human-male-female
          {% elif is_state('device_tracker.mi_mix_3', 'pokrov') %}
            mdi:home-group
          {% else %}
            mdi:help
          {% endif %}

      mamas_location:
        value_template: >-          
          {% if is_state('person.nastya', 'home') %}
            дома
          {% elif is_state('device_tracker.iphone_anastasiia', 'tushino') %}
            у бабушки
          {% elif is_state('device_tracker.iphone_anastasiia', 'altufevo') %}
            у родителей папы
          {% elif is_state('device_tracker.iphone_anastasiia', 'dimas_work') %}
            на работе у папы
          {% elif is_state('device_tracker.iphone_anastasiia', 'shiha') %}
            у родителей
          {% elif is_state('device_tracker.iphone_anastasiia', 'pokrov') %}
            на даче
          {% else %}
            где-то
          {% endif %}
        icon_template: >-
          {% if is_state('person.nastya', 'home') %}
            mdi:home
          {% elif is_state('device_tracker.iphone_anastasiia', 'tushino') %}
            mdi:face-woman
          {% elif is_state('device_tracker.iphone_anastasiia', 'altufevo') %}
            mdi:human-male-female
          {% elif is_state('device_tracker.iphone_anastasiia', 'dimas_work') %}
            mdi:office-building-marker-outline
          {% elif is_state('device_tracker.iphone_anastasiia', 'shiha') %}
            mdi:human-male-female
          {% elif is_state('device_tracker.iphone_anastasiia', 'pokrov') %}
            mdi:home-group
          {% else %}
            mdi:help
          {% endif %}
