sensor:
  - platform: time_date
    display_options:
      - 'time'

binary_sensor:
  - platform: workday
    country: RU

  - platform: template
    sensors:
      noise_allowed:
        value_template: >-
          {% set x = states('sensor.time') %}
          {% set hour = now().strftime("%H") | int  %}
          {{ states('binary_sensor.workday_sensor') == 'on' and ( ( hour >= 9 and hour < 13 ) or ( hour >= 15 and hour < 19) ) }}
        icon_template: >
          {% if is_state('binary_sensor.noise_allowed','on') %}
          mdi:volume-high
          {% else %}
          mdi:volume-off
          {% endif %}